---
title: Analysing Olympic Swimming History
author: Richie Rines
output: github_document
---

## Summary

This data analysis covers a dataset of all Swimming Olympic events from way back in 1912 to the most recent ones (as of writing this) in 2020. The dataset holds all the locations that the events took place in, respectively, the year they took place in, the distance and stroke that was swam, who swam it and what gender they were, whether or not the race was a relay, what country the swimmer represented, and of course their time and placement in the races. The data, however, has some flaws to it. It does not contain relays from the 2020 olympics. Also, the 2024 summer olympics are quickly approaching, and that means there will be new potential data entries that will NOT be a part of this dataset. Because of this, there is a possibility that some of the tables and/or graphs become less accurate or even flat-out false. 
With that disclaimer out of the way, the first thing I wanted to do with the data was determine how many events were in the olympics. I specifically wanted to see how the events featured at the 1912 games compared with the 2020 games. The results are surprising; the 1912 olympics only had eight events total, and only one of them was swam by women. This number is drastically different from the Olympics in 2020, which had a whopping 31 events! 1912 did not have individual medley (IM) events, but over the years IM events began to appear more and more in the games. IM means that the event is a combination of all four strokes (butterfly, backstroke, breaststroke, and freestyle), rather than just one. Another big change in the olympics was the addition of female-swam events. Every single event that has a men’s race also has a women’s race. This is a major reason the amount of events was bumped up to such a high number (31) in 2020 compared to the low number (8) in 1912. 
The next thing I was curious about was how frequent each stroke appeared over the whole course of the Olympic games. Using a bar graph, it was determined that freestyle was miles ahead of every other stroke. All of the strokes were evenly matched in frequency except for free. Naturally, I wanted to know why that was. Using a table, I found out that (for 2020) there were 15 freestyle events and the other 16 events were made up of other strokes. This immediately shows why the freestyle count is so high up there. In those 16 miscellaneous events (events that are not freestyle), the strokes are broken up fairly evenly throughout. There is relatively the same amount of backstroke, breaststroke, and butterfly events as well as a few IM events and relays being thrown into the mix. 
The Olympics is about showing the best athletes and which country brings the best swimmers to the competition. The goal of every race is to win, and all the wins are kept track of. How could there be a proper analysis without figuring out who is the best? That is, who has the most gold medals? Team USA takes the cake by a long shot. They have a grand total of 240 gold medals (wins) across all olympics. This sounds like a gigantic number, and that’s because it is. If we take a look at the team with the second-most gold medals, which is Australia (AUS), they only have 61. Granted, that is still an impressive number, but it looks tiny compared to the preposterous amount of gold medals USA has. And if we go even further and look at the team with the fifth-most golds, which is Japan, they only have 24. A bar graph shows that almost every time team USA entered the olympics, they won around half of the events. The same graph but of Australia instead shows that team AUS lost the large majority of the events they raced in. 
With all these teams receiving gold medals, many people wonder who the star athletes are. Who is winning all these races? According to a table, Michael Phelps (from Team USA) has the most individual gold medals out of all the athletes with a total of 13. And the second-place spot in the “Who Has the Most Gold Medals” table is also occupied by Team USA. Katie Ledecky has six gold medals. This is still not even half of what Phelps has! It goes to show that Michael Phelps really is dominating the games, one could even go so far as to say he is the king of the swimming olympics. 

```{r load-data, echo = FALSE}

```

## Presentation

My presentation can be found [here](presentation/presentation.html).

## Data 

Donut, D. S. (2023, April 18). Olympic swimming history (1912 to 2020). Kaggle. https://www.kaggle.com/datasets/datasciencedonut/olympic-swimming-1912-to-2020?resource=download 

## References

This is the dataset I used:

Donut, D. S. (2023, April 18). Olympic swimming history (1912 to 2020). Kaggle. https://www.kaggle.com/datasets/datasciencedonut/olympic-swimming-1912-to-2020?resource=download 

