---
title: "Analysing Olympic Swimming History"
subtitle: "From 1912 to 2020"
author: "Richie Rines"
institute: "Houghton University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r load-packages, include = FALSE}
# Add any additional packages you need to this chunk
library(tidyverse)
library(tidymodels)
library(palmerpenguins)
library(knitr)
library(xaringanthemer)
```

```{r setup, include=FALSE}
# For better figure resolution
knitr::opts_chunk$set(fig.retina = 3, dpi = 300, fig.width = 8, fig.asp = 0.618, out.width = "82%", fig.align = "center")
```

```{r load-data, include=FALSE}
data <- read.csv("Olympic_Swimming_Results_1912to2020.csv")
```

```{r, echo=FALSE}
style_xaringan(
  title_slide_background_image = "img/swimming.png"
)
```


class: center, middle

## Goal:
##To Analyze Olympic Swimming Results

---

# Number of Events

```{r}
data <- data %>%
  mutate(didWin = if_else(Rank == 1, "yes", "no"))

data %>%
  filter(didWin == "yes", Year == "1912" | Year == "2016") %>%
  group_by(Year) %>%
  count() %>%
  select(Year, n) %>%
  summarise(Events = n)
```

---

# 1912 events

```{r}
data %>%
  filter(didWin == "yes", Year == "1912") %>%
  select(Year, Distance..in.meters., Stroke, Gender)
```

---

# 2016 events

```{r}
data %>%
  filter(didWin == "yes", Year == "2016", Gender == "Men") %>%
  select(Year, Distance..in.meters., Stroke, Gender)
```
---

# Stroke Frequency

```{r, echo = FALSE}
data %>%
  ggplot(aes(x = Stroke, fill = Gender)) +
  geom_bar(color = "black", linewidth = 0.3) +
  scale_fill_manual(values = c("#77F3FF","#F98CE5")) +
  labs(x = "Stroke", 
       y = "Frequency", 
       title = "How Frequent Each Stroke is in the Olympics", 
       subtitle = "And the genders that swim them")
```

---

# Whole Lotta Free

```{r}
data %>%
  mutate(TempStroke = if_else(Stroke == "Freestyle", "Freestyle", "Other")) %>%
  filter(didWin == "yes", Year == "2016") %>%
  count(TempStroke)
```

---

# Most Successful Countries

```{r}
data %>%
  filter(didWin == "yes") %>%
  group_by(Team) %>%
  count(didWin) %>%
  select(Team, n) %>%
  summarise(Wins = n) %>%
  arrange(desc(Wins)) %>%
  slice(1, 2, 3, 4, 5)
```

---

# USA Plot

```{r, echo = FALSE}
data %>%
  mutate(USAwinlose = if_else(Rank == 1, "Wins", "Losses")) %>%
  filter(Team == "USA") %>%
  ggplot(aes(y = USAwinlose, fill = USAwinlose)) +
  geom_bar(color = "black", linewidth = 0.3) +
  scale_fill_manual(values = c("#FF0505","#74EF00")) +
  facet_wrap(. ~ Year) +
  labs(title = "USA Placements in Swimming Events Over the Years",
       subtitle = "From 1912 to 2020",
       x = "Wins/Losses",
       y = "",
       fill = "")
```

---

# AUS Plot

```{r, echo = FALSE}
data %>%
  mutate(AUSwinlose = if_else(Rank == 1, "Wins", "Losses")) %>%
  filter(Team == "AUS") %>%
  ggplot(aes(y = AUSwinlose, fill = AUSwinlose)) +
  geom_bar(color = "black", linewidth = 0.3) +
  scale_fill_manual(values = c("#ED294A","#3FE241")) +
  facet_wrap(. ~ Year) +
  labs(title = "Australia (AUS) Placements in Swimming Events Over the Years",
       subtitle = "From 1912 to 2020 (with different colors to further seperate from previous graph)",
       x = "Wins/Losses",
       y = "",
       fill = "")
```

---

# Most Successful Athletes

```{r}
data %>%
  filter(didWin == "yes") %>%
  group_by(Athlete) %>%
  count(didWin) %>%
  select(Athlete, n) %>%
  summarise(Wins = n) %>%
  arrange(desc(Wins)) %>%
  slice(1, 2, 3, 4, 5, 6, 7, 8, 9)
```